# Generated by Django 4.0.2 on 2022-02-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_rename_name_category_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='new',
            field=models.CharField(default='new', max_length=10, verbose_name='new stuff'),
            preserve_default=False,
        ),
    ]
